name: smartypants
description: A Dart package that provides text formatting similar to SmartyPants.
version: 0.0.2
repository: https://github.com/eunice-hong/smartypants

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0