name: Chore / Task
description: Internal task, refactor, or dependency update.
title: "[Chore] "
labels: [ "chore" ]
body:
  - type: textarea
    id: task
    attributes:
      label: Task Details
      placeholder: Describe the work needed.
      value: |
        - [ ] ...
  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: Why this task is needed.