name: Documentation Update
description: Report missing or outdated documentation.
title: "[Docs] "
labels: [ "documentation" ]
body:
  - type: input
    id: doc_section
    attributes:
      label: Affected Section or File
      placeholder: e.g., README.md → Installation
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Explain what should be updated or added.